server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amall
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service-mio
mybatis:
  type-aliases-package: com.mio4.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka



